/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Processor and features
 */
#undef  CONFIG_i386
#define CONFIG_PENTIUMI 1
#undef  CONFIG_PENTIUMII
#undef  CONFIG_PENTIUMIII

/*
 * BIOS (Basic Input Output System)
 */
#define CONFIG_BIOS_APM 1

/*
 * Hardware
 */
#undef  CONFIG_MEMTESTS

/*
 * Configure Agnix drivers
 */
#define CONFIG_DRIVERS_CHAR 1
#define CONFIG_DRIVERS_BLOCK 1
#define CONFIG_DRIVERS_NET 1
#undef  CONFIG_DRIVERS_NET_3c59x
#define CONFIG_DRIVERS_NET_RTL_8029 1

/*
 * Network protocols
 */
#define CONFIG_NET_LAYER_2_ETH 1
#undef  CONFIG_NET_LAYER_2_TR
