#define UTS_VERSION "#621 Fri Oct 1 22:13:36 CEST 2004"
#define AGNIX_COMPILE_TIME "22:13:36"
#define AGNIX_COMPILE_BY "root"
#define AGNIX_COMPILE_HOST "corvetta"
#define AGNIX_COMPILE_DOMAIN ""
#define AGNIX_COMPILE_PLATFORM "Linux"
#define AGNIX_COMPILER "gcc version 3.1.1"
