#define UTS_VERSION "#503 Thu Aug 19 20:38:33 CEST 2004"
#define AGNIX_COMPILE_TIME "20:38:33"
#define AGNIX_COMPILE_BY "root"
#define AGNIX_COMPILE_HOST "toreto"
#define AGNIX_COMPILE_DOMAIN ""
#define AGNIX_COMPILE_PLATFORM "Linux"
#define AGNIX_COMPILER "gcc version 3.1"
