#
# kernel_super/signals/Makefile
#
# Copyright (c) 2003-2004 Lukasz Dembinski <dembol@linux.net>
# All Rights Reserved
# 
# Date:		2004/07
# Author: 	Lukasz Dembinski
# Info:		Makefile
# Contact:	mailto: <dembol@linux.net>
#

OBJ-y  = signals.o sigaction.o
OBJ_LINK = $(OBJ-y)
OBJ_TARGET = skrn_signals.o

include $(TOP_DIR)/common.make