#
# kernel_sys/Makefile
#
# Copyright (c) 2003-2004 Lukasz Dembinski <dembol@linux.net>
# All Rights Reserved
# 
# Date:		2004/07
# Author: 	Lukasz Dembinski
# Info:		Makefile
# Contact:	mailto: <dembol@linux.net>
#

OBJ-y  = fork.o machine.o panic.o printk.o resources.o sys_unix.o \
syscalls.o thread.o time.o
OBJ_LINK = $(OBJ-y)
OBJ_TARGET = krn_sys.o

include $(TOP_DIR)/common.make