#
# kernel_net/layer_2/eth/Makefile
#
# Copyright (c) 2003-2004 Lukasz Dembinski <dembol@linux.net>
# All Rights Reserved
# 
# Date:		2004/07
# Author: 	Lukasz Dembinski
# Info:		Makefile
# Contact:	mailto: <dembol@linux.net>
#

OBJ-y  = net_core.o
# net_devices.o
OBJ_LINK = $(OBJ-y)
OBJ_TARGET = core.o

include $(TOP_DIR)/common.make