#
# kernel_super/memory/Makefile
#
# Copyright (c) 2003-2004 Lukasz Dembinski <dembol@linux.net>
# All Rights Reserved
# 
# Date:		2004/07
# Author: 	Lukasz Dembinski
# Info:		Makefile
# Contact:	mailto: <dembol@linux.net>
#

OBJ-y  = address.o alloc.o bin_alloc.o buddy_alloc.o slab_alloc.o
OBJ_LINK = $(OBJ-y)
OBJ_TARGET = skrn_memory.o

include $(TOP_DIR)/common.make