#
# kernel_super/init/Makefile
#
# Copyright (c) 2003-2004 Lukasz Dembinski <dembol@linux.net>
# All Rights Reserved
# 
# Date:		2004/07
# Author: 	Lukasz Dembinski
# Info:		Makefile
# Contact:	mailto: <dembol@linux.net>
#

OBJ-y  	  := counters_core.o counters_sys.o
OBJ_LINK  := $(OBJ-y)
OBJ_TARGET = skrn_counters.o

include $(TOP_DIR)/common.make