#
# kernel_drivers/adi_core/Makefile
#
# Copyright (c) 2003-2004 Lukasz Dembinski <dembol@linux.net>
# All Rights Reserved
# 
# Date:		2004/07
# Author: 	Lukasz Dembinski
# Info:		Makefile
# Contact:	mailto: <dembol@linux.net>
#

OBJ-y = floppy.o
OBJ_LINK = $(OBJ-y)
OBJ_TARGET = adi_blk_drv.o

include $(TOP_DIR)/common.make
